### ISSUE TITLE
Can we have WebBrowser<T extends WebElement> extends BrowserTest<T> ?

### ISSUE THREAD

**Issue by pvbemmelen62** [praegus/toolchain-fixtures#38]
I have a class VnwWebBrowser derived from WebBrowser derived from BrowserTest&lt;WebElement> .
BrowserTest defines the method
<pre>
    protected T getElement(String place) {
        return getSeleniumHelper().getElement(place);
    }
</pre>
where the <code>T</code> comes from
<pre>
public class BrowserTest&lt;T extends WebElement> extends SlimFixture {
</pre>

I want to override that method in VnwWebBrowser , and currently have the code
<pre>
  @Override
  protected WebElement getElement(String place) {
    place = vernieuwingPlace(place);
    return super.getElement(place);
  }
</pre>
I would prefer it to be
<pre>
  @Override
  protected T getElement(String place) {
    place = vernieuwingPlace(place);
    return super.getElement(place);
  }
</pre>
That is, have return type <code>T</code> rather than WebElement.
That way the method would be more similar to the original in BrowserTest .
That requires that
<pre>
public class WebBrowser extends BrowserTest<WebElement> {
</pre>
is changed to
<pre>
public class WebBrowser&lt;T extends WebElement> extends BrowserTest&lt;T> {
</pre>

Is that a change that can be made ?

**Comment by tcnh** [comment]
Sorry for the major delay, I thought we'd already done this. This is fixed in 1.36-JDK11
